# Adapted from FitFolio https://github.com/kbaggott1/FitFolio

name: Code Quality Workflow

on:
  pull_request:
    branches:
      - main
      
jobs:
  my_job:
    name: Build and Lint

    runs-on: ubuntu-latest

    steps:
    - name: Clone Repo
      uses: actions/checkout@v1

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Grant Execute Permission to gradlew
      run: chmod +x ./gradlew
      
    - name: Run the ktlintFormat command to format our files
      run: ./gradlew ktlintFormat

    - name: Run Kotlin Linter
      run: ./gradlew ktlintCheck
      
    - name: Run lintFix to attempt to fix linting errors
      run: ./gradlew lintFix

    - name: Run Android Linter
      run: ./gradlew lint

    - name: Build the application
      run: ./gradlew build
