# Adapted from:
# - FitFolio https://github.com/kbaggott1/FitFolio
# - https://stackoverflow.com/a/65857032

name: Code Quality Workflow

on:
  pull_request:
    branches:
      
jobs:
  my_job:
    name: Build and Lint
    runs-on: ubuntu-latest
    strategy:
      matrix: { dir: ["NavigationCodelab", "AdvancedStateAndSideEffectsCodelab"] }
    defaults:
      run: 
        working-directory: ${{ matrix.dir }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
    - uses: gradle/gradle-build-action@v2
    - run: chmod +x ./gradlew
    - run: ./gradlew ktlintFormat
    - run: ./gradlew ktlintCheck
    - run: ./gradlew lintFix
    - run: ./gradlew lint
    - run: ./gradlew build
